# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 02 Sep 2025 01:56:10 +0300
*               @ALL          0
*               @user         8
