# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 02 Sep 2025 01:56:10 +0300
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

ioanc1:$2y$10$sWK0wwASItP3LHWCINxJzOJq2Prajo7XET8Jxkjw0FEb0yBWQpLtC:Ioan :ioan@projectivi.ro:admin,user
